### PR TITLE
add ModulPower

### PR DESCRIPTION
**Pull request by joe288**
with the ModulPower commando you can e.g. turn a MIC 600TL-X into a MIC 1000TL-X

### CODE REVIEW

**Comment by nygma2004** [comment]
@joe288 thanks for adding this. How did you find this information? I have a MIC 1500TL-X, so potentially I can also override that as well? Do you have any ideas what the limitation could be?

**Comment by joe288** [comment]
Hi, I got the information from a German forum.
[https://www.photovoltaikforum.com/thread/171200-growatt-mic-serie-600-2000-wie-ist-leistungsvariante-codiert/?pageNo=1](url)
The MIC 1500TL-X can be encoded up to 2000W. In the forum someone set his MIC 600TL-X to 2000W without any problems.

In the data sheet of the Growatt you can clearly see that the same hardware is probably used from 600W to 2000W.

Unbenannt

**Comment by nygma2004** [comment]
Thanks a lot, indeed it makes sense. And we can also monitor the internal temperature and draw some conclusion from that as well. Or if over temperature fault codes start to show up.

**Comment by nygma2004** [comment]
One more question. I just got a new "[issue](https://github.com/nygma2004/growatt2mqtt/issues/19)" raised asking to specify a licence for the repository. He mentions that he is preferring MIT. I have no preference at all, and not knowledgeable about picking the correct license. I feel like besides the a framework, most of the knowledge on this project is the modbus protocol format published by Growatt. But since you made major contributions to this project, I wanted to ask you if you have any reservations for MIT licence.

**Pull request merged**
